"""Build 200 benign target memories with template-derived embeddings.

Each record is generated by a fresh benign probe.  The target agent receives
only its two normal tools; the attack tool is retained as retrieval provenance
and is never exposed to the agent.  The full episode text is stored unchanged,
while its vector is computed from ``TASK``, ``AVAILABLE_TOOLS``, and the normal
tools actually present in ``TOOLS_USED``.
"""

from __future__ import annotations

import argparse
import csv
import hashlib
import json
import math
import os
import shutil
import sys
import time
import uuid
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Iterable, Mapping

from attack_agent.api_retry import install_openai_api_retries
from attack_agent.local_model_config import (
    configure_target_openai_env,
    register_openai_compatible_target_model,
)
from attack_agent.mem0_builder import build_configurable_mem0_adapter
from attack_agent.run_adaptive_attack import (
    add_enable_thinking_argument,
    env_bool,
    is_api_failed,
    load_attack_agent_env,
    load_experiment_specs,
    log_event,
    max_tokens_limit_for_args,
    run_target_with_failure_guard,
)
from attack_agent.target_runner import ASBTargetRunner
from attack_agent.template.memory_retrieval_templates import (
    build_memory_embedding_text,
    extract_tools_used,
)


ASB_ROOT = Path(__file__).resolve().parents[3]
DEFAULT_OUTPUT_ROOT = ASB_ROOT / "memory_db" / "target_agent_mem0_with_embedding_init"
DEFAULT_LOG_ROOT = Path(__file__).resolve().parent / "logs"
RESULT_HEADER = [
    "agent",
    "task_index",
    "attack_tool_index",
    "attack_tool",
    "tools_used",
    "original_success",
    "api_failed",
    "row_elapsed_seconds",
]


def _json_names(names: Iterable[str]) -> str:
    return json.dumps(sorted(set(names)), ensure_ascii=False, separators=(",", ":"))


def _memory_payload(
    *,
    memory_id: str,
    memory_text: str,
    metadata: Mapping[str, Any],
    user_id: str,
    agent_id: str,
) -> dict[str, Any]:
    now = datetime.now(timezone.utc).isoformat()
    payload = dict(metadata)
    payload.update(
        {
            "user_id": user_id,
            "agent_id": agent_id,
            "role": "user",
            "data": memory_text,
            "hash": hashlib.md5(memory_text.encode("utf-8")).hexdigest(),
            "created_at": now,
            "updated_at": now,
            "text_lemmatized": memory_text,
        }
    )
    payload.setdefault("memory_id", memory_id)
    return payload


class TemplateEmbeddingMemoryWriter:
    """Mem0-compatible writer that decouples stored text from embedded text."""

    def __init__(
        self,
        *,
        base_adapter: Any,
        normal_tool_names: Iterable[str],
        embedding_model_name: str,
    ) -> None:
        self.memory = base_adapter.memory
        self.user_id = base_adapter.user_id
        self.agent_id = base_adapter.agent_id
        self.namespace = base_adapter.namespace
        self.normal_tool_names = frozenset(normal_tool_names)
        self.embedding_model_name = embedding_model_name
        self._last_sequence_ns = 0

        if len(self.normal_tool_names) != 2:
            raise ValueError(
                "A benign init probe must have exactly two normal tools; "
                f"found {sorted(self.normal_tool_names)!r}."
            )

    def _next_sequence_ns(self) -> int:
        sequence = max(time.time_ns(), self._last_sequence_ns + 1)
        self._last_sequence_ns = sequence
        return sequence

    def add_texts(
        self,
        texts: Iterable[str] | str,
        metadatas: Iterable[Mapping[str, Any]] | None = None,
        ids: Iterable[str] | None = None,
        **_: Any,
    ) -> list[dict[str, Any]]:
        text_list = [texts] if isinstance(texts, str) else list(texts)
        metadata_list = list(metadatas or ({} for _ in text_list))
        id_list = list(ids) if ids is not None else [str(uuid.uuid4()) for _ in text_list]
        if not (len(text_list) == len(metadata_list) == len(id_list)):
            raise ValueError("texts, metadatas, and ids must have the same length")

        results: list[dict[str, Any]] = []
        vector_store = self.memory.vector_store
        embedding_model = self.memory.embedding_model
        for memory_id, memory_text, raw_metadata in zip(
            id_list, text_list, metadata_list
        ):
            metadata = dict(raw_metadata)
            task = str(metadata.pop("_embedding_task", "")).strip()
            if not task:
                raise ValueError("Missing private _embedding_task metadata")
            construction_started_at = metadata.pop(
                "_construction_started_perf_counter",
                None,
            )
            if construction_started_at is None:
                raise ValueError(
                    "Missing private _construction_started_perf_counter metadata"
                )
            construction_started_at = float(construction_started_at)

            tools_used = extract_tools_used(memory_text)
            if not tools_used:
                raise ValueError("Benign probe did not execute a recognizable normal tool")
            unexpected_tools = set(tools_used) - self.normal_tool_names
            if unexpected_tools:
                raise ValueError(
                    "Benign probe used a non-normal tool: "
                    f"{sorted(unexpected_tools)!r}"
                )

            attack_tool = str(metadata.get("attack_tool", "")).strip()
            if not attack_tool:
                raise ValueError("Missing attack_tool provenance label")
            available_tools = sorted(self.normal_tool_names | {attack_tool})
            if len(available_tools) != 3:
                raise ValueError(
                    "Expected two normal tools plus one distinct attack tool; "
                    f"found {available_tools!r}"
                )

            embedding_text = build_memory_embedding_text(
                task,
                available_tools,
                tools_used,
            )
            embedding = list(embedding_model.embed(embedding_text, "add"))
            if not embedding or not all(math.isfinite(float(value)) for value in embedding):
                raise ValueError("Embedding API returned an empty or non-finite vector")
            if not any(float(value) != 0.0 for value in embedding):
                raise ValueError("Embedding API returned an all-zero vector")

            metadata.update(
                {
                    "namespace": self.namespace,
                    "memory_sequence_ns": self._next_sequence_ns(),
                    "tools_used": _json_names(tools_used),
                    "available_tools": _json_names(available_tools),
                    "normal_tools": _json_names(self.normal_tool_names),
                    "attack_tool_exposed": 0,
                    "embedding_text": embedding_text,
                    "embedding_template_version": "task_available_tools_used_v2",
                    "embedding_model": self.embedding_model_name,
                }
            )
            payload = _memory_payload(
                memory_id=memory_id,
                memory_text=str(memory_text),
                metadata=metadata,
                user_id=self.user_id,
                agent_id=self.agent_id,
            )
            vector_store.insert(
                vectors=[embedding],
                ids=[memory_id],
                payloads=[payload],
            )
            memory_record = {
                "id": memory_id,
                "memory": str(memory_text),
                "metadata": payload,
            }
            construction_elapsed_seconds = time.perf_counter() - construction_started_at
            log_event(
                "BENIGN_INIT_MEMORY_CREATED",
                construction_elapsed_seconds=round(
                    construction_elapsed_seconds,
                    6,
                ),
                embedding_text=f"\n{embedding_text}",
                memory_record=json.dumps(
                    memory_record,
                    ensure_ascii=False,
                    indent=2,
                ),
            )
            results.append(
                {
                    "id": memory_id,
                    "memory": str(memory_text),
                    "event": "ADD",
                    "role": "user",
                }
            )
        return results

    def add_documents(self, documents: Iterable[Any], **kwargs: Any) -> list[Any]:
        documents = list(documents)
        return self.add_texts(
            [getattr(document, "page_content", str(document)) for document in documents],
            metadatas=[getattr(document, "metadata", {}) or {} for document in documents],
            **kwargs,
        )

    def persist(self) -> None:
        return None


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "Run five tasks by forty attack-tool labels as benign probes and write "
            "200 memories whose vectors embed TASK, AVAILABLE_TOOLS, and "
            "actually used normal tools."
        )
    )
    parser.add_argument("--target_agent", default="system_admin_agent")
    parser.add_argument("--tasks_path", default="data/agent_task.jsonl")
    parser.add_argument("--attacker_tools_path", default="data/all_attack_tools.jsonl")
    parser.add_argument("--tools_info_path", default="data/all_normal_tools.jsonl")
    parser.add_argument("--task_num", type=int, default=5)
    parser.add_argument("--attack_tool_num", type=int, default=40)
    parser.add_argument("--output_root", type=Path, default=DEFAULT_OUTPUT_ROOT)
    parser.add_argument("--res_file", type=Path, default=None)
    parser.add_argument("--log_file", type=Path, default=None)
    parser.add_argument("--overwrite_init_memory", action="store_true")

    parser.add_argument(
        "--llm_name",
        default=os.getenv("ATTACK_TARGET_LLM_NAME", os.getenv("TARGET_LLM_NAME", "gpt-4o-mini")),
    )
    parser.add_argument(
        "--target_openai_base_url",
        default=os.getenv("ATTACK_TARGET_OPENAI_BASE_URL", os.getenv("OPENAI_BASE_URL")),
    )
    parser.add_argument(
        "--target_openai_api_key",
        default=os.getenv("ATTACK_TARGET_OPENAI_API_KEY", os.getenv("OPENAI_API_KEY")),
    )
    parser.add_argument(
        "--target_openai_compatible",
        action=argparse.BooleanOptionalAction,
        default=env_bool("ATTACK_TARGET_OPENAI_COMPATIBLE", False),
    )
    add_enable_thinking_argument(parser)
    parser.set_defaults(enable_thinking=False)
    parser.add_argument("--max_new_tokens", type=int, default=128)
    parser.add_argument("--api_max_retries", type=int, default=3)
    parser.add_argument("--api_retry_sleep", type=float, default=5.0)
    parser.add_argument("--use_backend", default="None", choices=["None", "ollama", "vllm"])
    parser.add_argument("--log_mode", default="console", choices=["console", "file"])

    parser.add_argument("--mem0_llm_model", default=os.getenv("MEM0_LLM_MODEL", "gpt-4o-mini"))
    parser.add_argument("--mem0_llm_provider", default="openai")
    parser.add_argument("--mem0_llm_base_url", default=os.getenv("MEM0_LLM_BASE_URL", os.getenv("OPENAI_BASE_URL")))
    parser.add_argument("--mem0_llm_api_key", default=os.getenv("MEM0_LLM_API_KEY", os.getenv("OPENAI_API_KEY")))
    parser.add_argument("--mem0_embedding_model", default=os.getenv("MEM0_EMBEDDING_MODEL", "text-embedding-3-small"))
    parser.add_argument("--mem0_embedding_provider", default="openai")
    parser.add_argument("--mem0_embedding_base_url", default=os.getenv("MEM0_EMBEDDING_BASE_URL", os.getenv("OPENAI_BASE_URL")))
    parser.add_argument("--mem0_embedding_api_key", default=os.getenv("MEM0_EMBEDDING_API_KEY", os.getenv("OPENAI_API_KEY")))
    return parser.parse_args()


def _load_normal_tool_names(path: Path, agent_name: str) -> tuple[str, ...]:
    names: set[str] = set()
    with path.open("r", encoding="utf-8") as input_file:
        for line in input_file:
            row = json.loads(line)
            if row.get("Corresponding Agent") == agent_name:
                name = str(row.get("Tool Name", "")).strip()
                if name:
                    names.add(name)
    if len(names) != 2:
        raise ValueError(
            f"Expected exactly two normal tools for {agent_name}, found {sorted(names)!r}"
        )
    return tuple(sorted(names))


def _reset_output(path: Path, *, overwrite: bool) -> None:
    resolved = path.resolve()
    if resolved == Path(resolved.anchor):
        raise ValueError("Refusing to use the filesystem root as output")
    if not path.exists():
        return
    if not path.is_dir():
        raise NotADirectoryError(path)
    if not overwrite:
        raise FileExistsError(
            f"Init memory already exists: {path}. Pass --overwrite_init_memory to rebuild it."
        )
    shutil.rmtree(path)


def _append_result(path: Path, row: list[Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    new_file = not path.exists()
    with path.open("a", newline="", encoding="utf-8") as output:
        writer = csv.writer(output)
        if new_file:
            writer.writerow(RESULT_HEADER)
        writer.writerow(row)


def run(args: argparse.Namespace) -> None:
    if args.task_num != 5 or args.attack_tool_num != 40:
        raise ValueError("This builder requires --task_num 5 and --attack_tool_num 40")
    if args.mem0_embedding_provider != "openai":
        raise ValueError("This builder currently requires an OpenAI-compatible embedding API")
    if args.use_backend == "None":
        args.use_backend = None

    output_path = args.output_root / f"target_agent_mem0_{args.target_agent}_init"
    result_path = args.res_file or DEFAULT_LOG_ROOT / f"{args.target_agent}.csv"
    _reset_output(output_path, overwrite=args.overwrite_init_memory)
    if result_path.exists() and not args.overwrite_init_memory:
        raise FileExistsError(
            f"Result file already exists: {result_path}. Pass --overwrite_init_memory to rebuild it."
        )
    if result_path.exists():
        result_path.unlink()

    args.target_mem0_path = str(output_path)
    args.target_mem0_collection = f"asb_mem0_normal_{args.target_agent}"
    args.target_mem0_user_id = f"asb_normal_{args.target_agent}"
    args.target_mem0_top_k = 10
    args.target_mem0_infer = False
    args.disable_target_memory = False

    max_tokens_limit = max_tokens_limit_for_args(args)
    os.environ["TARGET_MAX_TOKENS_LIMIT"] = str(
        max(int(os.getenv("TARGET_MAX_TOKENS_LIMIT", "0")), max_tokens_limit)
    )
    configure_target_openai_env(
        api_key=args.target_openai_api_key,
        base_url=args.target_openai_base_url,
    )
    if args.target_openai_compatible:
        register_openai_compatible_target_model(args.llm_name)
    install_openai_api_retries(
        max_retries=args.api_max_retries,
        retry_sleep=args.api_retry_sleep,
    )

    specs = load_experiment_specs(args)
    if len(specs) != 200:
        raise ValueError(f"Expected exactly 200 task/tool specs, found {len(specs)}")
    normal_tools = _load_normal_tool_names(Path(args.tools_info_path), args.target_agent)

    base_adapter = build_configurable_mem0_adapter(
        path=str(output_path),
        collection_name=args.target_mem0_collection,
        user_id=args.target_mem0_user_id,
        agent_id=args.target_agent,
        top_k=10,
        infer=False,
        llm_model=args.mem0_llm_model,
        embedding_model=args.mem0_embedding_model,
        namespace="adaptive_target_normal",
        llm_provider=args.mem0_llm_provider,
        llm_api_key=args.mem0_llm_api_key,
        llm_base_url=args.mem0_llm_base_url,
        embedding_provider=args.mem0_embedding_provider,
        embedding_api_key=args.mem0_embedding_api_key,
        embedding_base_url=args.mem0_embedding_base_url,
        enable_thinking=args.enable_thinking,
        retrieval_mode="tool_then_recent",
        use_real_embedding=True,
    )
    memory_writer = TemplateEmbeddingMemoryWriter(
        base_adapter=base_adapter,
        normal_tool_names=normal_tools,
        embedding_model_name=args.mem0_embedding_model,
    )
    target_runner = ASBTargetRunner(
        llm_name=args.llm_name,
        tools_info_path=args.tools_info_path,
        vector_db=memory_writer,
        read_db=False,
        write_db=True,
        max_new_tokens=args.max_new_tokens,
        use_backend=args.use_backend,
        log_mode=args.log_mode,
        enable_thinking=args.enable_thinking,
    )

    failures = 0
    try:
        log_event(
            "BENIGN_INIT_START",
            agent=args.target_agent,
            init_memory=output_path,
            expected_records=200,
            normal_tools=_json_names(normal_tools),
            attack_tool_exposed=0,
        )
        for index, spec in enumerate(specs, start=1):
            started_at = time.perf_counter()
            attack_tool = str(spec["attacker_tool"]["Attacker Tool"])
            task = str(spec["task"])
            task_index = (index - 1) // 40 + 1
            attack_tool_index = (index - 1) % 40 + 1
            observation = run_target_with_failure_guard(
                args=args,
                target_runner=target_runner,
                agent_path=spec["agent_path"],
                agent_name=spec["agent_name"],
                task=task,
                # The attack tool is a metadata label only. It is not added to
                # the target agent's runtime tool list.
                attacker_tool=None,
                attacked=False,
                strategy=None,
                context=[],
                read_target_memory=False,
                write_target_memory=True,
                memory_metadata={
                    "source": "init_benign_seed",
                    "phase": "benign_bootstrap",
                    "attack_tool": attack_tool,
                    "task_hash": hashlib.sha256(task.encode("utf-8")).hexdigest()[:16],
                    "task_index": task_index,
                    "attack_tool_index": attack_tool_index,
                    "benign_seed_index": index,
                    "_embedding_task": task,
                    "_construction_started_perf_counter": started_at,
                },
                call_site="init_benign_seed",
            )
            failed = is_api_failed(observation)
            failures += int(failed)
            memory_text = ""
            if isinstance(observation.raw_result, Mapping):
                # Logging only; the writer independently validates the exact
                # memory text passed by ASBTargetRunner.
                memory_text = str(observation.raw_result.get("messages_for_memory", ""))
            tools_used = extract_tools_used(memory_text)
            _append_result(
                result_path,
                [
                    args.target_agent,
                    task_index,
                    attack_tool_index,
                    attack_tool,
                    _json_names(tools_used),
                    int(observation.original_success),
                    int(failed),
                    round(time.perf_counter() - started_at, 6),
                ],
            )
    finally:
        target_runner.close()

    collection_count = int(base_adapter.memory.vector_store.collection.count())
    log_event(
        "BENIGN_INIT_END",
        agent=args.target_agent,
        init_memory=output_path,
        stored_records=collection_count,
        failed_records=failures,
    )
    if failures or collection_count != 200:
        raise RuntimeError(
            "Benign init construction is incomplete: "
            f"failures={failures}, stored_records={collection_count}, expected=200"
        )


class _TeeStream:
    """Mirror process output to the terminal and a persistent run log."""

    def __init__(self, terminal: Any, log_file: Any) -> None:
        self.terminal = terminal
        self.log_file = log_file

    def write(self, text: str) -> int:
        self.terminal.write(text)
        self.log_file.write(text)
        return len(text)

    def flush(self) -> None:
        self.terminal.flush()
        self.log_file.flush()

    def isatty(self) -> bool:
        return bool(getattr(self.terminal, "isatty", lambda: False)())


def main() -> None:
    load_attack_agent_env()
    args = parse_args()
    log_path = args.log_file or DEFAULT_LOG_ROOT / f"{args.target_agent}.log"
    if log_path.exists() and not args.overwrite_init_memory:
        raise FileExistsError(
            f"Log file already exists: {log_path}. "
            "Pass --overwrite_init_memory to rebuild it."
        )
    log_path.parent.mkdir(parents=True, exist_ok=True)

    original_stdout = sys.stdout
    original_stderr = sys.stderr
    with log_path.open("w", encoding="utf-8", buffering=1) as log_output:
        sys.stdout = _TeeStream(original_stdout, log_output)
        sys.stderr = _TeeStream(original_stderr, log_output)
        try:
            log_event("BENIGN_INIT_LOG", log_file=log_path)
            run(args)
        finally:
            sys.stdout = original_stdout
            sys.stderr = original_stderr


if __name__ == "__main__":
    main()
